var wms_layers = [];


        var lyr_CartoVoyagerLabels_0 = new ol.layer.Tile({
            'title': 'Carto Voyager Labels',
            'type': 'base',
            'opacity': 1.000000,
            
            
            source: new ol.source.XYZ({
    attributions: ' ',
                url: 'https://cartodb-basemaps-a.global.ssl.fastly.net/rastertiles/voyager/{z}/{x}/{y}.png'
            })
        });
var format_Parks_500ftBuffer_1 = new ol.format.GeoJSON();
var features_Parks_500ftBuffer_1 = format_Parks_500ftBuffer_1.readFeatures(json_Parks_500ftBuffer_1, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_Parks_500ftBuffer_1 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_Parks_500ftBuffer_1.addFeatures(features_Parks_500ftBuffer_1);
var lyr_Parks_500ftBuffer_1 = new ol.layer.Vector({
                declutter: true,
                source:jsonSource_Parks_500ftBuffer_1, 
                style: style_Parks_500ftBuffer_1,
                interactive: true,
                title: '<img src="styles/legend/Parks_500ftBuffer_1.png" /> Parks_500ftBuffer'
            });
var format_ChicagoParks_2 = new ol.format.GeoJSON();
var features_ChicagoParks_2 = format_ChicagoParks_2.readFeatures(json_ChicagoParks_2, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_ChicagoParks_2 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_ChicagoParks_2.addFeatures(features_ChicagoParks_2);
var lyr_ChicagoParks_2 = new ol.layer.Vector({
                declutter: true,
                source:jsonSource_ChicagoParks_2, 
                style: style_ChicagoParks_2,
                interactive: true,
                title: '<img src="styles/legend/ChicagoParks_2.png" /> Chicago - Parks'
            });
var format_ChicagoBoundaries_3 = new ol.format.GeoJSON();
var features_ChicagoBoundaries_3 = format_ChicagoBoundaries_3.readFeatures(json_ChicagoBoundaries_3, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_ChicagoBoundaries_3 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_ChicagoBoundaries_3.addFeatures(features_ChicagoBoundaries_3);
var lyr_ChicagoBoundaries_3 = new ol.layer.Vector({
                declutter: true,
                source:jsonSource_ChicagoBoundaries_3, 
                style: style_ChicagoBoundaries_3,
                interactive: true,
                title: '<img src="styles/legend/ChicagoBoundaries_3.png" /> Chicago - Boundaries'
            });
var format_tobaccoLicenses_4 = new ol.format.GeoJSON();
var features_tobaccoLicenses_4 = format_tobaccoLicenses_4.readFeatures(json_tobaccoLicenses_4, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_tobaccoLicenses_4 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_tobaccoLicenses_4.addFeatures(features_tobaccoLicenses_4);
var lyr_tobaccoLicenses_4 = new ol.layer.Vector({
                declutter: true,
                source:jsonSource_tobaccoLicenses_4, 
                style: style_tobaccoLicenses_4,
                interactive: true,
                title: '<img src="styles/legend/tobaccoLicenses_4.png" /> tobaccoLicenses'
            });
var format_tobaccoLicenses_within500ftParks_5 = new ol.format.GeoJSON();
var features_tobaccoLicenses_within500ftParks_5 = format_tobaccoLicenses_within500ftParks_5.readFeatures(json_tobaccoLicenses_within500ftParks_5, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_tobaccoLicenses_within500ftParks_5 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_tobaccoLicenses_within500ftParks_5.addFeatures(features_tobaccoLicenses_within500ftParks_5);
var lyr_tobaccoLicenses_within500ftParks_5 = new ol.layer.Vector({
                declutter: true,
                source:jsonSource_tobaccoLicenses_within500ftParks_5, 
                style: style_tobaccoLicenses_within500ftParks_5,
                interactive: true,
                title: '<img src="styles/legend/tobaccoLicenses_within500ftParks_5.png" /> tobaccoLicenses_within500ftParks'
            });
var format_Dispensaries_Chicago_6 = new ol.format.GeoJSON();
var features_Dispensaries_Chicago_6 = format_Dispensaries_Chicago_6.readFeatures(json_Dispensaries_Chicago_6, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_Dispensaries_Chicago_6 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_Dispensaries_Chicago_6.addFeatures(features_Dispensaries_Chicago_6);
var lyr_Dispensaries_Chicago_6 = new ol.layer.Vector({
                declutter: true,
                source:jsonSource_Dispensaries_Chicago_6, 
                style: style_Dispensaries_Chicago_6,
                interactive: true,
                title: '<img src="styles/legend/Dispensaries_Chicago_6.png" /> Dispensaries_Chicago'
            });

lyr_CartoVoyagerLabels_0.setVisible(true);lyr_Parks_500ftBuffer_1.setVisible(true);lyr_ChicagoParks_2.setVisible(true);lyr_ChicagoBoundaries_3.setVisible(true);lyr_tobaccoLicenses_4.setVisible(true);lyr_tobaccoLicenses_within500ftParks_5.setVisible(true);lyr_Dispensaries_Chicago_6.setVisible(true);
var layersList = [lyr_CartoVoyagerLabels_0,lyr_Parks_500ftBuffer_1,lyr_ChicagoParks_2,lyr_ChicagoBoundaries_3,lyr_tobaccoLicenses_4,lyr_tobaccoLicenses_within500ftParks_5,lyr_Dispensaries_Chicago_6];
lyr_Parks_500ftBuffer_1.set('fieldAliases', {'acres': 'acres', 'archery_ra': 'archery_ra', 'artificial': 'artificial', 'band_shell': 'band_shell', 'baseball_b': 'baseball_b', 'baseball_j': 'baseball_j', 'baseball_s': 'baseball_s', 'basketba_1': 'basketba_1', 'basketball': 'basketball', 'beach': 'beach', 'boat_lau_1': 'boat_lau_1', 'boat_launc': 'boat_launc', 'boat_slips': 'boat_slips', 'bocce_cour': 'bocce_cour', 'bowling_gr': 'bowling_gr', 'boxing_cen': 'boxing_cen', 'carousel': 'carousel', 'casting_pi': 'casting_pi', 'climbing_w': 'climbing_w', 'community_': 'community_', 'conservato': 'conservato', 'cricket_fi': 'cricket_fi', 'croquet': 'croquet', 'cultural_c': 'cultural_c', 'dog_friend': 'dog_friend', 'fitness_ce': 'fitness_ce', 'fitness_co': 'fitness_co', 'football_s': 'football_s', 'gallery': 'gallery', 'game_table': 'game_table', 'garden': 'garden', 'gisobjid': 'gisobjid', 'golf_cours': 'golf_cours', 'golf_drivi': 'golf_drivi', 'golf_putti': 'golf_putti', 'gymnasium': 'gymnasium', 'gymnastic_': 'gymnastic_', 'handball_i': 'handball_i', 'handball_r': 'handball_r', 'harbor': 'harbor', 'horseshoe_': 'horseshoe_', 'iceskating': 'iceskating', 'label': 'label', 'lagoon': 'lagoon', 'location': 'location', 'minigolf': 'minigolf', 'modeltrain': 'modeltrain', 'modelyacht': 'modelyacht', 'mountain_b': 'mountain_b', 'nature_bir': 'nature_bir', 'nature_cen': 'nature_cen', 'objectid_1': 'objectid_1', 'park': 'park', 'park_class': 'park_class', 'park_no': 'park_no', 'perimeter': 'perimeter', 'playgrou_1': 'playgrou_1', 'playground': 'playground', 'pool_indoo': 'pool_indoo', 'pool_outdo': 'pool_outdo', 'rowing_clu': 'rowing_clu', 'senior_cen': 'senior_cen', 'shape_area': 'shape_area', 'shape_leng': 'shape_leng', 'shuffleboa': 'shuffleboa', 'skate_park': 'skate_park', 'sled_hill': 'sled_hill', 'sport_roll': 'sport_roll', 'spray_feat': 'spray_feat', 'tennis_cou': 'tennis_cou', 'track': 'track', 'volleyba_1': 'volleyba_1', 'volleyball': 'volleyball', 'ward': 'ward', 'water_play': 'water_play', 'water_slid': 'water_slid', 'wetland_ar': 'wetland_ar', 'wheelchr_a': 'wheelchr_a', 'zip': 'zip', 'zoo': 'zoo', });
lyr_ChicagoParks_2.set('fieldAliases', {'acres': 'acres', 'archery_ra': 'archery_ra', 'artificial': 'artificial', 'band_shell': 'band_shell', 'baseball_b': 'baseball_b', 'baseball_j': 'baseball_j', 'baseball_s': 'baseball_s', 'basketba_1': 'basketba_1', 'basketball': 'basketball', 'beach': 'beach', 'boat_lau_1': 'boat_lau_1', 'boat_launc': 'boat_launc', 'boat_slips': 'boat_slips', 'bocce_cour': 'bocce_cour', 'bowling_gr': 'bowling_gr', 'boxing_cen': 'boxing_cen', 'carousel': 'carousel', 'casting_pi': 'casting_pi', 'climbing_w': 'climbing_w', 'community_': 'community_', 'conservato': 'conservato', 'cricket_fi': 'cricket_fi', 'croquet': 'croquet', 'cultural_c': 'cultural_c', 'dog_friend': 'dog_friend', 'fitness_ce': 'fitness_ce', 'fitness_co': 'fitness_co', 'football_s': 'football_s', 'gallery': 'gallery', 'game_table': 'game_table', 'garden': 'garden', 'gisobjid': 'gisobjid', 'golf_cours': 'golf_cours', 'golf_drivi': 'golf_drivi', 'golf_putti': 'golf_putti', 'gymnasium': 'gymnasium', 'gymnastic_': 'gymnastic_', 'handball_i': 'handball_i', 'handball_r': 'handball_r', 'harbor': 'harbor', 'horseshoe_': 'horseshoe_', 'iceskating': 'iceskating', 'label': 'label', 'lagoon': 'lagoon', 'location': 'location', 'minigolf': 'minigolf', 'modeltrain': 'modeltrain', 'modelyacht': 'modelyacht', 'mountain_b': 'mountain_b', 'nature_bir': 'nature_bir', 'nature_cen': 'nature_cen', 'objectid_1': 'objectid_1', 'park': 'park', 'park_class': 'park_class', 'park_no': 'park_no', 'perimeter': 'perimeter', 'playgrou_1': 'playgrou_1', 'playground': 'playground', 'pool_indoo': 'pool_indoo', 'pool_outdo': 'pool_outdo', 'rowing_clu': 'rowing_clu', 'senior_cen': 'senior_cen', 'shape_area': 'shape_area', 'shape_leng': 'shape_leng', 'shuffleboa': 'shuffleboa', 'skate_park': 'skate_park', 'sled_hill': 'sled_hill', 'sport_roll': 'sport_roll', 'spray_feat': 'spray_feat', 'tennis_cou': 'tennis_cou', 'track': 'track', 'volleyba_1': 'volleyba_1', 'volleyball': 'volleyball', 'ward': 'ward', 'water_play': 'water_play', 'water_slid': 'water_slid', 'wetland_ar': 'wetland_ar', 'wheelchr_a': 'wheelchr_a', 'zip': 'zip', 'zoo': 'zoo', });
lyr_ChicagoBoundaries_3.set('fieldAliases', {'name': 'name', 'objectid': 'objectid', 'shape_area': 'shape_area', 'shape_len': 'shape_len', });
lyr_tobaccoLicenses_4.set('fieldAliases', {'field_1': 'field_1', 'ID': 'ID', 'LICENSE.ID': 'LICENSE.ID', 'ACCOUNT.NUMBER': 'ACCOUNT.NUMBER', 'SITE.NUMBER': 'SITE.NUMBER', 'LEGAL.NAME': 'LEGAL.NAME', 'DOING.BUSINESS.AS.NAME': 'DOING.BUSINESS.AS.NAME', 'ADDRESS': 'ADDRESS', 'CITY': 'CITY', 'STATE': 'STATE', 'ZIP.CODE': 'ZIP.CODE', 'WARD': 'WARD', 'PRECINCT': 'PRECINCT', 'WARD.PRECINCT': 'WARD.PRECINCT', 'POLICE.DISTRICT': 'POLICE.DISTRICT', 'LICENSE.CODE': 'LICENSE.CODE', 'LICENSE.DESCRIPTION': 'LICENSE.DESCRIPTION', 'BUSINESS.ACTIVITY.ID': 'BUSINESS.ACTIVITY.ID', 'BUSINESS.ACTIVITY': 'BUSINESS.ACTIVITY', 'LICENSE.NUMBER': 'LICENSE.NUMBER', 'APPLICATION.TYPE': 'APPLICATION.TYPE', 'APPLICATION.CREATED.DATE': 'APPLICATION.CREATED.DATE', 'APPLICATION.REQUIREMENTS.COMPLETE': 'APPLICATION.REQUIREMENTS.COMPLETE', 'PAYMENT.DATE': 'PAYMENT.DATE', 'CONDITIONAL.APPROVAL': 'CONDITIONAL.APPROVAL', 'LICENSE.TERM.START.DATE': 'LICENSE.TERM.START.DATE', 'LICENSE.TERM.EXPIRATION.DATE': 'LICENSE.TERM.EXPIRATION.DATE', 'LICENSE.APPROVED.FOR.ISSUANCE': 'LICENSE.APPROVED.FOR.ISSUANCE', 'DATE.ISSUED': 'DATE.ISSUED', 'LICENSE.STATUS': 'LICENSE.STATUS', 'LICENSE.STATUS.CHANGE.DATE': 'LICENSE.STATUS.CHANGE.DATE', 'SSA': 'SSA', 'LATITUDE': 'LATITUDE', 'LONGITUDE': 'LONGITUDE', 'LOCATION': 'LOCATION', });
lyr_tobaccoLicenses_within500ftParks_5.set('fieldAliases', {'field_1': 'field_1', 'ID': 'ID', 'LICENSE.ID': 'LICENSE.ID', 'ACCOUNT.NU': 'ACCOUNT.NU', 'SITE.NUMBE': 'SITE.NUMBE', 'LEGAL.NAME': 'LEGAL.NAME', 'DOING.BUSI': 'DOING.BUSI', 'ADDRESS': 'ADDRESS', 'CITY': 'CITY', 'STATE': 'STATE', 'ZIP.CODE': 'ZIP.CODE', 'WARD': 'WARD', 'PRECINCT': 'PRECINCT', 'WARD.PRECI': 'WARD.PRECI', 'POLICE.DIS': 'POLICE.DIS', 'LICENSE.CO': 'LICENSE.CO', 'LICENSE.DE': 'LICENSE.DE', 'BUSINESS.A': 'BUSINESS.A', 'BUSINESS_1': 'BUSINESS_1', 'LICENSE.NU': 'LICENSE.NU', 'APPLICATIO': 'APPLICATIO', 'APPLICAT_1': 'APPLICAT_1', 'APPLICAT_2': 'APPLICAT_2', 'PAYMENT.DA': 'PAYMENT.DA', 'CONDITIONA': 'CONDITIONA', 'LICENSE.TE': 'LICENSE.TE', 'LICENSE._1': 'LICENSE._1', 'LICENSE.AP': 'LICENSE.AP', 'DATE.ISSUE': 'DATE.ISSUE', 'LICENSE.ST': 'LICENSE.ST', 'LICENSE._2': 'LICENSE._2', 'SSA': 'SSA', 'LATITUDE': 'LATITUDE', 'LONGITUDE': 'LONGITUDE', 'LOCATION': 'LOCATION', });
lyr_Dispensaries_Chicago_6.set('fieldAliases', {'Name': 'Name', 'Address': 'Address', 'Latitude': 'Latitude', 'Longitude': 'Longitude', 'field_5': 'field_5', 'field_6': 'field_6', 'field_7': 'field_7', 'field_8': 'field_8', 'field_9': 'field_9', });
lyr_Parks_500ftBuffer_1.set('fieldImages', {'acres': 'TextEdit', 'archery_ra': 'TextEdit', 'artificial': 'TextEdit', 'band_shell': 'TextEdit', 'baseball_b': 'TextEdit', 'baseball_j': 'TextEdit', 'baseball_s': 'TextEdit', 'basketba_1': 'TextEdit', 'basketball': 'TextEdit', 'beach': 'TextEdit', 'boat_lau_1': 'TextEdit', 'boat_launc': 'TextEdit', 'boat_slips': 'TextEdit', 'bocce_cour': 'TextEdit', 'bowling_gr': 'TextEdit', 'boxing_cen': 'TextEdit', 'carousel': 'TextEdit', 'casting_pi': 'TextEdit', 'climbing_w': 'TextEdit', 'community_': 'TextEdit', 'conservato': 'TextEdit', 'cricket_fi': 'TextEdit', 'croquet': 'TextEdit', 'cultural_c': 'TextEdit', 'dog_friend': 'TextEdit', 'fitness_ce': 'TextEdit', 'fitness_co': 'TextEdit', 'football_s': 'TextEdit', 'gallery': 'TextEdit', 'game_table': 'TextEdit', 'garden': 'TextEdit', 'gisobjid': 'TextEdit', 'golf_cours': 'TextEdit', 'golf_drivi': 'TextEdit', 'golf_putti': 'TextEdit', 'gymnasium': 'TextEdit', 'gymnastic_': 'TextEdit', 'handball_i': 'TextEdit', 'handball_r': 'TextEdit', 'harbor': 'TextEdit', 'horseshoe_': 'TextEdit', 'iceskating': 'TextEdit', 'label': 'TextEdit', 'lagoon': 'TextEdit', 'location': 'TextEdit', 'minigolf': 'TextEdit', 'modeltrain': 'TextEdit', 'modelyacht': 'TextEdit', 'mountain_b': 'TextEdit', 'nature_bir': 'TextEdit', 'nature_cen': 'TextEdit', 'objectid_1': 'TextEdit', 'park': 'TextEdit', 'park_class': 'TextEdit', 'park_no': 'TextEdit', 'perimeter': 'TextEdit', 'playgrou_1': 'TextEdit', 'playground': 'TextEdit', 'pool_indoo': 'TextEdit', 'pool_outdo': 'TextEdit', 'rowing_clu': 'TextEdit', 'senior_cen': 'TextEdit', 'shape_area': 'TextEdit', 'shape_leng': 'TextEdit', 'shuffleboa': 'TextEdit', 'skate_park': 'TextEdit', 'sled_hill': 'TextEdit', 'sport_roll': 'TextEdit', 'spray_feat': 'TextEdit', 'tennis_cou': 'TextEdit', 'track': 'TextEdit', 'volleyba_1': 'TextEdit', 'volleyball': 'TextEdit', 'ward': 'TextEdit', 'water_play': 'TextEdit', 'water_slid': 'TextEdit', 'wetland_ar': 'TextEdit', 'wheelchr_a': 'TextEdit', 'zip': 'TextEdit', 'zoo': 'TextEdit', });
lyr_ChicagoParks_2.set('fieldImages', {'acres': 'TextEdit', 'archery_ra': 'TextEdit', 'artificial': 'TextEdit', 'band_shell': 'TextEdit', 'baseball_b': 'TextEdit', 'baseball_j': 'TextEdit', 'baseball_s': 'TextEdit', 'basketba_1': 'TextEdit', 'basketball': 'TextEdit', 'beach': 'TextEdit', 'boat_lau_1': 'TextEdit', 'boat_launc': 'TextEdit', 'boat_slips': 'TextEdit', 'bocce_cour': 'TextEdit', 'bowling_gr': 'TextEdit', 'boxing_cen': 'TextEdit', 'carousel': 'TextEdit', 'casting_pi': 'TextEdit', 'climbing_w': 'TextEdit', 'community_': 'TextEdit', 'conservato': 'TextEdit', 'cricket_fi': 'TextEdit', 'croquet': 'TextEdit', 'cultural_c': 'TextEdit', 'dog_friend': 'TextEdit', 'fitness_ce': 'TextEdit', 'fitness_co': 'TextEdit', 'football_s': 'TextEdit', 'gallery': 'TextEdit', 'game_table': 'TextEdit', 'garden': 'TextEdit', 'gisobjid': 'TextEdit', 'golf_cours': 'TextEdit', 'golf_drivi': 'TextEdit', 'golf_putti': 'TextEdit', 'gymnasium': 'TextEdit', 'gymnastic_': 'TextEdit', 'handball_i': 'TextEdit', 'handball_r': 'TextEdit', 'harbor': 'TextEdit', 'horseshoe_': 'TextEdit', 'iceskating': 'TextEdit', 'label': 'TextEdit', 'lagoon': 'TextEdit', 'location': 'TextEdit', 'minigolf': 'TextEdit', 'modeltrain': 'TextEdit', 'modelyacht': 'TextEdit', 'mountain_b': 'TextEdit', 'nature_bir': 'TextEdit', 'nature_cen': 'TextEdit', 'objectid_1': 'TextEdit', 'park': 'TextEdit', 'park_class': 'TextEdit', 'park_no': 'TextEdit', 'perimeter': 'TextEdit', 'playgrou_1': 'TextEdit', 'playground': 'TextEdit', 'pool_indoo': 'TextEdit', 'pool_outdo': 'TextEdit', 'rowing_clu': 'TextEdit', 'senior_cen': 'TextEdit', 'shape_area': 'TextEdit', 'shape_leng': 'TextEdit', 'shuffleboa': 'TextEdit', 'skate_park': 'TextEdit', 'sled_hill': 'TextEdit', 'sport_roll': 'TextEdit', 'spray_feat': 'TextEdit', 'tennis_cou': 'TextEdit', 'track': 'TextEdit', 'volleyba_1': 'TextEdit', 'volleyball': 'TextEdit', 'ward': 'TextEdit', 'water_play': 'TextEdit', 'water_slid': 'TextEdit', 'wetland_ar': 'TextEdit', 'wheelchr_a': 'TextEdit', 'zip': 'TextEdit', 'zoo': 'TextEdit', });
lyr_ChicagoBoundaries_3.set('fieldImages', {'name': 'TextEdit', 'objectid': 'TextEdit', 'shape_area': 'TextEdit', 'shape_len': 'TextEdit', });
lyr_tobaccoLicenses_4.set('fieldImages', {'field_1': 'Range', 'ID': 'TextEdit', 'LICENSE.ID': 'Range', 'ACCOUNT.NUMBER': 'Range', 'SITE.NUMBER': 'Range', 'LEGAL.NAME': 'TextEdit', 'DOING.BUSINESS.AS.NAME': 'TextEdit', 'ADDRESS': 'TextEdit', 'CITY': 'TextEdit', 'STATE': 'TextEdit', 'ZIP.CODE': 'Range', 'WARD': 'TextEdit', 'PRECINCT': 'TextEdit', 'WARD.PRECINCT': 'TextEdit', 'POLICE.DISTRICT': 'TextEdit', 'LICENSE.CODE': 'Range', 'LICENSE.DESCRIPTION': 'TextEdit', 'BUSINESS.ACTIVITY.ID': 'TextEdit', 'BUSINESS.ACTIVITY': 'TextEdit', 'LICENSE.NUMBER': 'Range', 'APPLICATION.TYPE': 'TextEdit', 'APPLICATION.CREATED.DATE': 'TextEdit', 'APPLICATION.REQUIREMENTS.COMPLETE': 'TextEdit', 'PAYMENT.DATE': 'TextEdit', 'CONDITIONAL.APPROVAL': 'TextEdit', 'LICENSE.TERM.START.DATE': 'TextEdit', 'LICENSE.TERM.EXPIRATION.DATE': 'TextEdit', 'LICENSE.APPROVED.FOR.ISSUANCE': 'TextEdit', 'DATE.ISSUED': 'TextEdit', 'LICENSE.STATUS': 'TextEdit', 'LICENSE.STATUS.CHANGE.DATE': 'TextEdit', 'SSA': 'TextEdit', 'LATITUDE': 'TextEdit', 'LONGITUDE': 'TextEdit', 'LOCATION': 'TextEdit', });
lyr_tobaccoLicenses_within500ftParks_5.set('fieldImages', {'field_1': 'TextEdit', 'ID': 'TextEdit', 'LICENSE.ID': 'TextEdit', 'ACCOUNT.NU': 'TextEdit', 'SITE.NUMBE': 'TextEdit', 'LEGAL.NAME': 'TextEdit', 'DOING.BUSI': 'TextEdit', 'ADDRESS': 'TextEdit', 'CITY': 'TextEdit', 'STATE': 'TextEdit', 'ZIP.CODE': 'TextEdit', 'WARD': 'TextEdit', 'PRECINCT': 'TextEdit', 'WARD.PRECI': 'TextEdit', 'POLICE.DIS': 'TextEdit', 'LICENSE.CO': 'TextEdit', 'LICENSE.DE': 'TextEdit', 'BUSINESS.A': 'TextEdit', 'BUSINESS_1': 'TextEdit', 'LICENSE.NU': 'TextEdit', 'APPLICATIO': 'TextEdit', 'APPLICAT_1': 'TextEdit', 'APPLICAT_2': 'TextEdit', 'PAYMENT.DA': 'TextEdit', 'CONDITIONA': 'TextEdit', 'LICENSE.TE': 'TextEdit', 'LICENSE._1': 'TextEdit', 'LICENSE.AP': 'TextEdit', 'DATE.ISSUE': 'TextEdit', 'LICENSE.ST': 'TextEdit', 'LICENSE._2': 'TextEdit', 'SSA': 'TextEdit', 'LATITUDE': 'TextEdit', 'LONGITUDE': 'TextEdit', 'LOCATION': 'TextEdit', });
lyr_Dispensaries_Chicago_6.set('fieldImages', {'Name': 'TextEdit', 'Address': 'TextEdit', 'Latitude': 'TextEdit', 'Longitude': 'TextEdit', 'field_5': 'TextEdit', 'field_6': 'TextEdit', 'field_7': 'TextEdit', 'field_8': 'TextEdit', 'field_9': 'TextEdit', });
lyr_Parks_500ftBuffer_1.set('fieldLabels', {'acres': 'no label', 'archery_ra': 'no label', 'artificial': 'no label', 'band_shell': 'no label', 'baseball_b': 'no label', 'baseball_j': 'no label', 'baseball_s': 'no label', 'basketba_1': 'no label', 'basketball': 'no label', 'beach': 'no label', 'boat_lau_1': 'no label', 'boat_launc': 'no label', 'boat_slips': 'no label', 'bocce_cour': 'no label', 'bowling_gr': 'no label', 'boxing_cen': 'no label', 'carousel': 'no label', 'casting_pi': 'no label', 'climbing_w': 'no label', 'community_': 'no label', 'conservato': 'no label', 'cricket_fi': 'no label', 'croquet': 'no label', 'cultural_c': 'no label', 'dog_friend': 'no label', 'fitness_ce': 'no label', 'fitness_co': 'no label', 'football_s': 'no label', 'gallery': 'no label', 'game_table': 'no label', 'garden': 'no label', 'gisobjid': 'no label', 'golf_cours': 'no label', 'golf_drivi': 'no label', 'golf_putti': 'no label', 'gymnasium': 'no label', 'gymnastic_': 'no label', 'handball_i': 'no label', 'handball_r': 'no label', 'harbor': 'no label', 'horseshoe_': 'no label', 'iceskating': 'no label', 'label': 'no label', 'lagoon': 'no label', 'location': 'no label', 'minigolf': 'no label', 'modeltrain': 'no label', 'modelyacht': 'no label', 'mountain_b': 'no label', 'nature_bir': 'no label', 'nature_cen': 'no label', 'objectid_1': 'no label', 'park': 'no label', 'park_class': 'no label', 'park_no': 'no label', 'perimeter': 'no label', 'playgrou_1': 'no label', 'playground': 'no label', 'pool_indoo': 'no label', 'pool_outdo': 'no label', 'rowing_clu': 'no label', 'senior_cen': 'no label', 'shape_area': 'no label', 'shape_leng': 'no label', 'shuffleboa': 'no label', 'skate_park': 'no label', 'sled_hill': 'no label', 'sport_roll': 'no label', 'spray_feat': 'no label', 'tennis_cou': 'no label', 'track': 'no label', 'volleyba_1': 'no label', 'volleyball': 'no label', 'ward': 'no label', 'water_play': 'no label', 'water_slid': 'no label', 'wetland_ar': 'no label', 'wheelchr_a': 'no label', 'zip': 'no label', 'zoo': 'no label', });
lyr_ChicagoParks_2.set('fieldLabels', {'acres': 'no label', 'archery_ra': 'no label', 'artificial': 'no label', 'band_shell': 'no label', 'baseball_b': 'no label', 'baseball_j': 'no label', 'baseball_s': 'no label', 'basketba_1': 'no label', 'basketball': 'no label', 'beach': 'no label', 'boat_lau_1': 'no label', 'boat_launc': 'no label', 'boat_slips': 'no label', 'bocce_cour': 'no label', 'bowling_gr': 'no label', 'boxing_cen': 'no label', 'carousel': 'no label', 'casting_pi': 'no label', 'climbing_w': 'no label', 'community_': 'no label', 'conservato': 'no label', 'cricket_fi': 'no label', 'croquet': 'no label', 'cultural_c': 'no label', 'dog_friend': 'no label', 'fitness_ce': 'no label', 'fitness_co': 'no label', 'football_s': 'no label', 'gallery': 'no label', 'game_table': 'no label', 'garden': 'no label', 'gisobjid': 'no label', 'golf_cours': 'no label', 'golf_drivi': 'no label', 'golf_putti': 'no label', 'gymnasium': 'no label', 'gymnastic_': 'no label', 'handball_i': 'no label', 'handball_r': 'no label', 'harbor': 'no label', 'horseshoe_': 'no label', 'iceskating': 'no label', 'label': 'no label', 'lagoon': 'no label', 'location': 'no label', 'minigolf': 'no label', 'modeltrain': 'no label', 'modelyacht': 'no label', 'mountain_b': 'no label', 'nature_bir': 'no label', 'nature_cen': 'no label', 'objectid_1': 'no label', 'park': 'no label', 'park_class': 'no label', 'park_no': 'no label', 'perimeter': 'no label', 'playgrou_1': 'no label', 'playground': 'no label', 'pool_indoo': 'no label', 'pool_outdo': 'no label', 'rowing_clu': 'no label', 'senior_cen': 'no label', 'shape_area': 'no label', 'shape_leng': 'no label', 'shuffleboa': 'no label', 'skate_park': 'no label', 'sled_hill': 'no label', 'sport_roll': 'no label', 'spray_feat': 'no label', 'tennis_cou': 'no label', 'track': 'no label', 'volleyba_1': 'no label', 'volleyball': 'no label', 'ward': 'no label', 'water_play': 'no label', 'water_slid': 'no label', 'wetland_ar': 'no label', 'wheelchr_a': 'no label', 'zip': 'no label', 'zoo': 'no label', });
lyr_ChicagoBoundaries_3.set('fieldLabels', {'name': 'no label', 'objectid': 'no label', 'shape_area': 'no label', 'shape_len': 'no label', });
lyr_tobaccoLicenses_4.set('fieldLabels', {'field_1': 'no label', 'ID': 'no label', 'LICENSE.ID': 'no label', 'ACCOUNT.NUMBER': 'no label', 'SITE.NUMBER': 'no label', 'LEGAL.NAME': 'no label', 'DOING.BUSINESS.AS.NAME': 'no label', 'ADDRESS': 'no label', 'CITY': 'no label', 'STATE': 'no label', 'ZIP.CODE': 'no label', 'WARD': 'no label', 'PRECINCT': 'no label', 'WARD.PRECINCT': 'no label', 'POLICE.DISTRICT': 'no label', 'LICENSE.CODE': 'no label', 'LICENSE.DESCRIPTION': 'no label', 'BUSINESS.ACTIVITY.ID': 'no label', 'BUSINESS.ACTIVITY': 'no label', 'LICENSE.NUMBER': 'no label', 'APPLICATION.TYPE': 'no label', 'APPLICATION.CREATED.DATE': 'no label', 'APPLICATION.REQUIREMENTS.COMPLETE': 'no label', 'PAYMENT.DATE': 'no label', 'CONDITIONAL.APPROVAL': 'no label', 'LICENSE.TERM.START.DATE': 'no label', 'LICENSE.TERM.EXPIRATION.DATE': 'no label', 'LICENSE.APPROVED.FOR.ISSUANCE': 'no label', 'DATE.ISSUED': 'no label', 'LICENSE.STATUS': 'no label', 'LICENSE.STATUS.CHANGE.DATE': 'no label', 'SSA': 'no label', 'LATITUDE': 'no label', 'LONGITUDE': 'no label', 'LOCATION': 'no label', });
lyr_tobaccoLicenses_within500ftParks_5.set('fieldLabels', {'field_1': 'no label', 'ID': 'no label', 'LICENSE.ID': 'no label', 'ACCOUNT.NU': 'no label', 'SITE.NUMBE': 'no label', 'LEGAL.NAME': 'no label', 'DOING.BUSI': 'no label', 'ADDRESS': 'no label', 'CITY': 'no label', 'STATE': 'no label', 'ZIP.CODE': 'no label', 'WARD': 'no label', 'PRECINCT': 'no label', 'WARD.PRECI': 'no label', 'POLICE.DIS': 'no label', 'LICENSE.CO': 'no label', 'LICENSE.DE': 'no label', 'BUSINESS.A': 'no label', 'BUSINESS_1': 'no label', 'LICENSE.NU': 'no label', 'APPLICATIO': 'no label', 'APPLICAT_1': 'no label', 'APPLICAT_2': 'no label', 'PAYMENT.DA': 'no label', 'CONDITIONA': 'no label', 'LICENSE.TE': 'no label', 'LICENSE._1': 'no label', 'LICENSE.AP': 'no label', 'DATE.ISSUE': 'no label', 'LICENSE.ST': 'no label', 'LICENSE._2': 'no label', 'SSA': 'no label', 'LATITUDE': 'no label', 'LONGITUDE': 'no label', 'LOCATION': 'no label', });
lyr_Dispensaries_Chicago_6.set('fieldLabels', {'Name': 'no label', 'Address': 'no label', 'Latitude': 'no label', 'Longitude': 'no label', 'field_5': 'no label', 'field_6': 'no label', 'field_7': 'no label', 'field_8': 'no label', 'field_9': 'no label', });
lyr_Dispensaries_Chicago_6.on('precompose', function(evt) {
    evt.context.globalCompositeOperation = 'normal';
});